STRIKES = {
    "Karate": {
                "Straight Right": (5, 7),
                "Straight Left": (6, 8),
                "Left Cross": (4, 6),
                "Right Cross": (4, 6),
                "Hook": (5, 7),
                "Uppercut": (6, 8),
                "Backfist": (4, 6),
                "Ridgehand": (5, 7),
                "Knifehand": (5, 7),
                "Palm Strike": (4, 6),
                "Hammerfist": (5, 7),
                "Spearhand": (6, 8),
                "Reverse Punch": (7, 9),
                "Reverse Knifehand": (7, 9),
                "Reverse Hammerfist": (7, 9),
                "Reverse Spearhand": (8, 10),
                "Reverse Backfist": (7, 9),
                "Reverse Ridgehand": (7, 9),
                "Chop": (4, 6),
                "Knee Strike": (5, 7)
            },
            "Muay-Thai": {
                "Elbow": (6, 8),
                "Khao Chiang – Diagonal Knee Strike": (5, 7),
                "Clinch": (4, 6),
                "Teep": (4, 6),
                "Khao Trong - Straight Knee Strike": (5, 7),
                "Thip Top – Slapping Foot Jab": (5, 6),
                "Low Kick": (5, 7),
                "High Kick": (6, 8),
                "Body Kick": (5, 7),
                "Uppercut": (5, 7),
                "Thip Khang – Side Foot Thrust": (5, 7),
                "Spinning Elbow": (7, 9),
                "Spinning Back Elbow": (7, 9),
                "Spinning Back Kick": (7, 9),
                "Te Klap Lang – Reverse Roundhouse Kick": (7, 9),
                "Te Kot – Downward Roundhouse Kick": (7, 9),
                "Khao Loi - Flying Knee": (9, 10),
                "Flying Elbow": (9, 10),
                "Flying Kick": (7, 9),
                "Superman Punch": (7, 9),
                "Jumping Knee": (7, 9),
                "Jumping Elbow": (7, 9)
            },
            "Aikido": {
                "Throw": (5, 7),
                "Lock": (4, 6),
                "Redirect": (3, 5),
                "Sweep": (4, 6),
                "Joint Lock": (5, 7),
                "Wrist Lock": (4, 6),
                "Arm Lock": (5, 7),
                "Shoulder Throw": (5, 7),
                "Hip Throw": (5, 7)
            },
            "Boxing": {
                "Jab": (4, 6),
                "Cross": (5, 7),
                "Hook": (5, 7),
                "Uppercut": (6, 8),
                "Weave": (3, 5),
                "Body Shot": (4, 6),
                "Left Hook": (5, 7),
                "Right Hook": (5, 7),
                "Left Straight": (5, 7),
                "Right Straight": (6, 8),
                "Overhand": (6, 8),
                "Counter": (8, 10)
            },
            "Kung-Fu": {
                "Palm Strike": (5, 7),
                "Sweep": (4, 6),
                "Dragon Strike": (5, 7),
                "Tiger Palm": (5, 7),
                "Crane Kick": (6, 8),
                "Mantis Strike": (5, 7),
                "Iron Fist": (6, 8),
                "Phoenix Eye Fist": (5, 7),
                "Monkey Strike": (5, 7),
                "Dragon Fist": (8, 10),
                "Tiger Fist": (7, 10),
                "Crane Fist": (6, 10),
                "Mantis Fist": (5, 7),
                "Monkey Fist": (5, 7),
                "Panda Fist": (5, 7),
            },
            "Judo": {
                "Throw": (5, 7),
                "Sweep": (4, 6),
                "Chokehold": (5, 7),
                "Armbar": (6, 8),
                "Hip Throw": (5, 7),
                "Ankle Pick": (4, 6),
                "Leg Sweep": (5, 7),
                "Shoulder Throw": (6, 8),
                "Counter Throw": (5, 7)
            },
            "Taekwondo": {
                "Spin Kick": (6, 8),
                "Front Kick": (5, 7),
                "Roundhouse Kick": (6, 8),
                "Axe Kick": (5, 7),
                "Back Kick": (6, 8),
                "Side Kick": (5, 7),
                "Crescent Kick": (6, 8),
                "Hook Kick": (5, 7),
                "Reverse Roundhouse": (6, 8),
                "Reverse Side Kick": (6, 8),
                "Reverse Hook Kick": (6, 8),
                "Reverse Crescent Kick": (6, 8),
                "Push Kick": (4, 6)
            },
            "Wrestling": {
                "Wild Punch": (6, 8),
                "Kick": (6, 8),
                "Slam": (6, 8),
                "Grapple": (5, 7),
                "Takedown": (5, 7),
                "Suplex": (6, 8),
                "Arm Drag": (4, 6),
                "Double Leg": (6, 8),
                "Single Leg": (5, 7),
                "Neck Crank": (5, 7),
                "Leg Lock": (6, 8)
            },
            "Kravmaga": {
                "Palm Strike": (6, 8),
                "Low Kick": (5, 7),
                "Knee Strike": (5, 7),
                "Eye Gouge": (4, 6),
                "Backhand": (5, 7),
                "Finger Strike": (5, 7),
                "Headbutt": (5, 7),
                "Short Elbow": (4, 6),
                "Hammerfist": (5, 7),
                "Inside Knee": (6, 8),
                "Elbow": (6, 8),
                "High Knee": (6, 8)
            },
            "Capoeira": {
                "Sweep": (5, 7),
                "Cartwheel": (4, 6),
                "Headbutt": (5, 7),
                "Spinning Kick": (6, 8),
                "Elbow Strike": (6, 8),
                "Spinning Elbow": (6, 8),
                "Knee Strike": (5, 7),
                "Handstand": (4, 6),
                "Backflip": (6, 8),
                "Front Kick": (5, 7),
                "Roundhouse Kick": (6, 8),
                "Axe Kick": (6, 8)
            },
            "Sambo": {
                "Throw": (5, 7),
                "Lock": (4, 6),
                "Sweep": (4, 6),
                "Chokehold": (5, 7),
                "Ankle Lock": (6, 8),
                "Knee Bar": (6, 8),
                "Armbar": (6, 8),
                "Leg Lock": (6, 8),
                "Wrist Lock": (5, 7),
                "Shoulder Lock": (5, 7),
                "Neck Crank": (6, 8),
                "Reverse Armbar": (6, 8),
                "Reverse Leg Lock": (6, 8)
            },
            "Kickboxing": {
                "Kick": (6, 8),
                "Straight Punch": (5, 7),
                "Hook": (5, 7),
                "Knee Strike": (5, 7),
                "Spinning Backfist": (6, 8),
                "Low Kick": (5, 7),
                "High Kick": (6, 8),
                "Body Kick": (5, 7),
                "Hook Kick": (6, 8),
                "Roundhouse Kick": (6, 8),
                "Axe Kick": (6, 8),
                "Side Kick": (5, 7),
                "Crescent Kick": (6, 8),
                "Reverse Roundhouse": (6, 8),
                "Reverse Side Kick": (6, 8)
            },
            "MMA": {
                "Left Straight": (6, 8),
                "Right Straight": (6, 8),
                "Hook": (5, 7),
                "Left Uppercut": (6, 8),
                "Right Uppercut": (6, 8),
                "Superman Punch": (7, 9),
                "Flying Knee": (7, 9),
                "Kick": (6, 8),
                "Submission": (4, 6),
                "Ground and Pound": (7, 9),
            "Rear Naked Choke": (9, 10)
            },
            "Brazilian Jiu-Jitsu": {
                "Armbar": (6, 8),
                "Triangle Choke": (5, 7),
                "Kimura": (6, 8),
                "Omoplata": (6, 8),
                "Rear Naked Choke": (6, 8),
                "Sweep": (4, 6),
                "Guard Pass": (5, 7),
                "Mount": (6, 8),
                "Back Take": (6, 8),
                "Darce Choke": (7, 9),
                "Guillotine": (7, 9),
                "Arm Triangle": (6, 8),
                "Heel Hook": (7, 9),
                "Toe Hold": (7, 9),
                "Knee Bar": (7, 9),
                "Straight Ankle Lock": (6, 8),
                "Wrist Lock": (5, 7),
                "Crucifix": (6, 8),
                "Loop Choke": (7, 9),
                "Bow and Arrow Choke": (7, 9),
                "Clock Choke": (6, 8),
                "Paper Cutter Choke": (7, 9),
                "Bread Cutter Choke": (8, 10)
            }
        }

BODY_PARTS = [
    "head", "chest", "left arm", "right arm", "nose", "neck", "left ear", "right ear",
    "teeth", "left leg", "right leg", "right foot", "left foot", "liver", "kidneys",
    "spine", "clavical", "left hip", "right hip", "left knee", "right knee", "solar plexus",
    "cranium", "kisser", "chin", "left shoulder", "right shoulder", "ass", "crotch", "spine", "ribs", "spinal column",
    "left ankle", "right ankle", "jaw", "left eye", "right eye", "stomach", "temple", "forehead", "mid-section"
]

GRAPPLE_ACTIONS = [
    "completes", "nails", "executes", "finishes", "performs", "grabs", "attains", "pulls off"]

GRAPPLE_KEYWORDS = [
    "Choke", "Mount", "Triangle", "Kimura", "Omoplata", "Crucifix", "Guillotine", "Lock", "Bar", "Hold", "Submission", "Crank", "Takedown", "Suplex", "Slam", "Throw", "Drag", "Take", "Redirect", "Chokehold", "Single Leg", "Double Leg"
]

STRIKE_ACTIONS = [
    "throws", "slams", "nails", "whacks", "connects", "rips", "thuds", "crushes", "snaps", "smashes", 
    "pounds", "cracks", "hits", "drives", "lands", "bashes", "clobbers", "wallops", "hammers",
    "strikes", "belts", "mashes", "pummels", "slugs", "batters", "blasts", "bludgeons", "thumps", "thwacks",
    "wacks", "whams", "socks", "smacks", "beats", "whomps", "whips", "thwumps", "clangs", "claps", "donks"
]

CRITICAL_MESSAGES = [
    "Channeling the power of the Dim Mak strike,",
    "Harnessing the technique bestowed upon them by the Black Dragon Fighting Society,",
    "Channeling the Grand Master Ashida Kim,",
    "Summoning the power of Count Dante,"
    "Channeling the power of the Black Dragon,",
    "Feeling the power of the Black Cobra,",
    "Feeling the power of the Black Dragon,",
    "Harnessing the strength of Master Yoshi,",
    "Unleashing the Chi energy of The Red Tiger,",
    "Summoning the spirit of The White Crane,",
    "Calling upon the secrets of the Shadow Serpent,",
    "Harnessing the precision of Master Liu Kang,",
    "Channeling the ferocity of the Jade Dragon,",
    "Invoking the techniques of the Phoenix Warrior,",
    "Invoking the force of the Midnight Panther,",
    "Channeling the might of the Storm Dragon,",
    "Drawing from the power of the Fire Phoenix,",
    "Summoning the power of the Tiger's Claw,",
    "Drawing from the legendary moves of the Tai Chi Tortoise,",
    "Unleashing the might of the Combat Corgi,",
    "Unleashing the fury of the Mighty Mongoose,",
    "Drawing from the legendary moves of the Tai Chi Terrier,",
    "Ivoking the techniques of Steven Segal,",
    "Recalling the power of Master Ti Ni Peen,",
    "Drawing from the legendary moves of Yung Ho,",
    "Channeling the power of Grand Master Chew Kok,",
    "Unleashing he power of Lo Hung Dong,",
    "Lifting the power of Phat Ho"
    
    
    
    
     
]

CRITICAL_RESULTS = {
    "{defender} is gasping for air!": "Punctured Lung",
    "{defender} suffers a broken nose!": "Broken Nose",
    "{defender} has a shattered rib!": "Shattered Rib",
    "{defender} winces in pain from a dislocated left shoulder!": "Dislocated Left Shoulder",
    "{defender} winces in pain from a dislocated right shoulder!": "Dislocated Right Shoulder",
    "{defender} holds their broken jaw!": "Broken Jaw",
    "{defender} appears dazed from a concussion!": "Concussion",
    "{defender} struggles with a broken right leg!": "Broken Right Leg",
    "{defender} struggles with a broken left leg!": "Broken Left Leg",
    "{defender} clutches their broken right arm!": "Broken Right Arm",
    "{defender} clutches their broken left arm!": "Broken Left Arm",
    "{defender} winces from a broken left collarbone!": "Broken Left Collarbone",
    "{defender} winces from a broken right collarbone!": "Broken Right Collarbone",
    "{defender} struggles with a broken left wrist!": "Broken Left Wrist",
    "{defender} struggles with a broken right wrist!": "Broken Right Wrist",
    "{defender} stumbles from a broken left ankle!": "Broken Ankle",
    "{defender} stumbles from a broken right ankle!": "Broken Ankle",
    "{defender} grimaces with a broken finger!": "Broken Finger",
    "{defender} grimaces with a broken toe!": "Broken Toe",
    "{defender} clutches their broken rib!": "Broken Rib",
    "{defender} is in pain from a broken shin!": "Broken Shin",
    "{defender} limps with a broken thigh!": "Broken Thigh",
    "{defender} cries out from a broken kneecap!": "Broken Kneecap",
    "{defender} struggles to stand with a broken left foot!": "Broken Left Foot",
    "{defender} struggles to stand with a broken right foot!": "Broken Right Foot",
    "{defender} holds their broken hand!": "Broken Hand",
    "{defender} has a cut over their eye!": "Cut Eye",
    "{defender} is sporting a black eye!": "Black Eye",
    "{defender} has a bloody nose!": "Bloody Nose",
    "{defender}'s nose is smashed and bloody!": "Broken Nose",
    "{defender} has a bloody lip!": "Cut Lip",
    "{defender} has a bloody ear!": "Damaged Eardrum",
    "{defender} spits blood from a cut mouth!": "Cut Mouth",
    "{defender} has a bloody forehead!": "Cut Forehead",
    "{defender} wipes blood from their cheek!": "Bloody Cheek",
    "{defender} suffers a detached left retina!": "Detached Left Retina",
    "{defender} suffers a detached right retina!": "Detached Right Retina",
    "{defender}'s left shoulder is in agony and appears broken!": "Broken Left Shoulder",
    "{defender}'s right shoulder is in agony and appears broken!": "Broken Right Shoulder",
    "{defender} has broken teeth!": "Broken Teeth",
    "{defender} is left with a fractured skull!": "Fractured Skull",
    "{defender} is left with a collapsed lung!": "Collapsed Lung",
    "{defender} is experiencing internal bleeding!": "Internal Bleeding",
    "{defender} is left with a ruptured spleen!": "Ruptured Spleen",
    "{defender} is dealing with a torn muscle!": "Torn Muscle",
    "{defender} is in agony from a dislocated knee!": "Dislocated Knee",
    "{defender} is suffering from a fractured pelvis!": "Fractured Pelvis",
    "{defender} is left with a split lip!": "Split Lip",
    "{defender} is clutching a cracked rib!": "Cracked Rib",
    "{defender} is dealing with a sprained wrist!": "Sprained Wrist",
    "{defender} is limping with a sprained ankle!": "Sprained Ankle",
    "{defender} has a deep cut on the arm!": "Deep Arm Cut",
    "{defender} has a deep cut on the leg!": "Deep Leg Cut",
    "{defender} is suffering from a torn ligament!": "Torn Ligament",
    "{defender} is wincing from a bruised rib!": "Bruised Rib",
    "{defender} is suffering from a bruised kidney!": "Bruised Kidney",
    "{defender} is left with a broken elbow!": "Broken Elbow",
    "{defender} is left with a broken kneecap!": "Broken Kneecap",
    "{defender} is suffering from a ruptured eardrum!": "Ruptured Eardrum",
    "{defender} has a cracked skull!": "Cracked Skull",
}

INJURY_TREATMENT_COST = {
    "Punctured Lung": 8300,
    "Broken Nose": 1150,
    "Shattered Rib": 6250,
    "Dislocated Left Shoulder": 2180,
    "Dislocated Right Shoulder": 2180,
    "Broken Jaw": 4220,
    "Concussion": 1300,
    "Broken Right Leg": 5270,
    "Broken Left Leg": 5270,
    "Broken Right Arm": 3240,
    "Broken Left Arm": 3240,
    "Broken Left Collarbone": 3260,
    "Broken Right Collarbone": 3260,
    "Broken Left Wrist": 1130,
    "Broken Right Wrist": 1130,
    "Broken Ankle": 1140,
    "Broken Finger": 1150,
    "Broken Toe": 1140,
    "Broken Rib": 1250,
    "Broken Shin": 1120,
    "Broken Thigh": 1230,
    "Broken Kneecap": 1210,
    "Broken Left Foot": 1160,
    "Broken Right Foot": 1160,
    "Broken Hand": 1190,
    "Cut Eye": 110,
    "Black Eye": 180,
    "Bloody Nose": 160,
    "Cut Lip": 170,
    "Damaged Eardrum": 1190,
    "Cut Mouth": 100,
    "Cut Forehead": 130,
    "Bloody Cheek": 120,
    "Detached Left Retina": 4100,
    "Detached Right Retina": 4100,
    "Broken Left Shoulder": 1180,
    "Broken Right Shoulder": 1180,
    "Broken Teeth": 1300,
    "Fractured Skull": 5400,
    "Collapsed Lung": 5350,
    "Internal Bleeding": 5500,
    "Ruptured Spleen": 10450,
    "Torn Muscle": 6200,
    "Dislocated Knee": 4200,
    "Fractured Pelvis": 10400,
    "Split Lip": 170,
    "Cracked Rib": 6230,
    "Sprained Wrist": 1100,
    "Sprained Ankle": 1100,
    "Deep Arm Cut": 1150,
    "Deep Leg Cut": 1150,
    "Torn Ligament": 1300,
    "Bruised Rib": 1180,
    "Bruised Kidney": 5120,
    "Broken Elbow": 4220,
    "Ruptured Eardrum": 3100,
    "Cracked Skull": 5400,
}




KO_MESSAGES = [
    "{loser} got knocked the fuck out!",
    "{loser} got KO'd!",
    "{loser} is out cold!",
    "{loser} got knocked out!",
    "{loser} is seeing glimpses of the afterlife!",
    "{loser} is unresponsive!",
    "{loser} is out like a light!",
    "{loser} got flattened!",
    "{loser} got their lights turned off!",
    "{loser} is unconscious!",
    "{loser} got put to sleep!",
    "{loser} got sent to the shadow realm!",
    "{loser} got laid out!",
    "{loser} is out of commission!"
]

TKO_MESSAGES = [
    "{loser} is out on his feet!",
    "{loser} is hurt!",
    "{loser} is just trying to survive!",
    "{loser} is doing the skanky leg!",
    "{loser} is in survival mode!",
    "{loser} is getting hurt in there!",
    "{loser} is wobbled!",
    "{loser} is wobbling!",
    "{loser} is in dire straits!",
    "{loser} is in deep trouble!",
    "{loser} is struggling to stay up!",
    "{loser} is struggling to stay on their feet!",
    "{loser} is barely standing!",
    "{loser} is on shaky legs!"
    
]

SUBMISSION_MESSAGES = [
    "{loser} tapped!",
    "{loser} wants out, they tapped!",
    "There's the tap, {loser} has had enough!",
    "{loser} tapped like a bitch!"
]

FIGHT_RESULT_LONG = {
    "UD": "Unanimous Decision",
    "SD": "Split Decision",
    "KO": "Knock Out",
    "TKO": "Technical Knock Out"
}

REFEREE_STOPS = [
    "Herb Dean has seen enough!",
    "The referee has seen enough!",
    "The referee stops it!",
    "Yves Lavigne is thinking of stopping it, its over!",
    "Big John steps in!",
    "The ref is stopping this!",
    "Mario Yamasaki is trying to stop it!",
    "The ref is about to call this one!",
    "The ref has called a halt to the fight!",
    "The referee waves it off!",
    "The ref signals the end!",
    "Yves Lavigne has seen enough, he stops it!",
    "Big John puts an end to it!",
    "The ref jumps in, it's over!",
    "Big John calls a stop to the action!",
    "Herb Dean has seen enough, it's over folks!",
    "The ref calls it, fight's over!"
]

TKO_VICTOR_MESSAGE = [
    "bringing the pain!",
    "ended that brutally!",
    "is a monster! ",
    "is a beast! ",
    "had bad intentions!",
    "showed some serious power",
    "sends a message to their challengers",
    "made a statement!",
    "was relentless!",
    "was a force of nature!",
    "overwhelmed their opponent!",
    "brought the hammer down!",
    "brought the pain!",
    "proved their might!",
    "is unstoppable!",
    "showed no mercy!",
    "struck with precision and power!",
    "proved their dominance!",
    "crushed their foe!"
]

KO_VICTOR_MESSAGE = [
    "Beat them into a living death!",
    "is an absolute beast!",
    "is an absolute monster!",
    "has some heavy hands!",
    "made a statement!",
    "put him to sleep!",
    "sends a message to their challengers",
    "had bad intentions!",
    "sent him to sleep!",
    "turned out the lights!",
    "delivered a knockout blow!",
    "sent shockwaves through the arena!",
    "brought the hammer down!",
    "dropped them with authority!",
    "left them seeing stars!",
    "is a savage!",
    "put them out with a barrage of power!"
]

ACTION_COST = 10