STRIKES = {
    "Karate": {
                "Straight Right": (5, 7),
                "Straight Left": (6, 8),
                "Left Cross": (4, 6),
                "Right Cross": (4, 6),
                "Hook": (5, 7),
                "Uppercut": (6, 8),
                "Backfist": (4, 6),
                "Ridgehand": (5, 7),
                "Knifehand": (5, 7),
                "Palm Strike": (4, 6),
                "Hammerfist": (5, 7),
                "Spearhand": (6, 8),
                "Reverse Punch": (7, 9),
                "Reverse Knifehand": (7, 9),
                "Reverse Hammerfist": (7, 9),
                "Reverse Spearhand": (8, 10),
                "Reverse Backfist": (7, 9),
                "Reverse Ridgehand": (7, 9),
                "Chop": (4, 6),
                "Knee Strike": (5, 7)
            },
            "Muay-Thai": {
                "Elbow": (6, 8),
                "Khao Chiang – Diagonal Knee Strike": (5, 7),
                "Clinch": (4, 6),
                "Teep": (4, 6),
                "Khao Trong - Straight Knee Strike": (5, 7),
                "Thip Top – Slapping Foot Jab": (5, 6),
                "Low Kick": (5, 7),
                "High Kick": (6, 8),
                "Body Kick": (5, 7),
                "Uppercut": (5, 7),
                "Thip Khang – Side Foot Thrust": (5, 7),
                "Spinning Elbow": (7, 9),
                "Spinning Back Elbow": (7, 9),
                "Spinning Back Kick": (7, 9),
                "Te Klap Lang – Reverse Roundhouse Kick": (7, 9),
                "Te Kot – Downward Roundhouse Kick": (7, 9),
                "Khao Loi - Flying Knee": (9, 10),
                "Flying Elbow": (9, 10),
                "Flying Kick": (7, 9),
                "Superman Punch": (7, 9),
                "Jumping Knee": (7, 9),
                "Jumping Elbow": (7, 9)
            },
            "Aikido": {
                "Throw": (5, 7),
                "Lock": (4, 6),
                "Redirect": (3, 5),
                "Sweep": (4, 6),
                "Joint Lock": (5, 7),
                "Wrist Lock": (4, 6),
                "Arm Lock": (5, 7),
                "Shoulder Throw": (5, 7),
                "Hip Throw": (5, 7)
            },
            "Boxing": {
                "Jab": (4, 6),
                "Cross": (5, 7),
                "Hook": (5, 7),
                "Uppercut": (6, 8),
                "Weave": (3, 5),
                "Body Shot": (4, 6),
                "Left Hook": (5, 7),
                "Right Hook": (5, 7),
                "Left Straight": (5, 7),
                "Right Straight": (6, 8),
                "Overhand": (6, 8),
                "Counter": (8, 10)
            },
            "Kung-Fu": {
                "Palm Strike": (5, 7),
                "Sweep": (4, 6),
                "Dragon Strike": (5, 7),
                "Tiger Palm": (5, 7),
                "Crane Kick": (6, 8),
                "Mantis Strike": (5, 7),
                "Iron Fist": (6, 8),
                "Phoenix Eye Fist": (5, 7),
                "Monkey Strike": (5, 7),
                "Dragon Fist": (8, 10),
                "Tiger Fist": (7, 10),
                "Crane Fist": (6, 10),
                "Mantis Fist": (5, 7),
                "Monkey Fist": (5, 7),
                "Panda Fist": (5, 7),
            },
            "Judo": {
                "Throw": (5, 7),
                "Sweep": (4, 6),
                "Chokehold": (5, 7),
                "Armbar": (6, 8),
                "Hip Throw": (5, 7),
                "Ankle Pick": (4, 6),
                "Leg Sweep": (5, 7),
                "Shoulder Throw": (6, 8),
                "Counter Throw": (5, 7)
            },
            "Taekwondo": {
                "Spin Kick": (6, 8),
                "Front Kick": (5, 7),
                "Roundhouse Kick": (6, 8),
                "Axe Kick": (5, 7),
                "Back Kick": (6, 8),
                "Side Kick": (5, 7),
                "Crescent Kick": (6, 8),
                "Hook Kick": (5, 7),
                "Reverse Roundhouse": (6, 8),
                "Reverse Side Kick": (6, 8),
                "Reverse Hook Kick": (6, 8),
                "Reverse Crescent Kick": (6, 8),
                "Push Kick": (4, 6)
            },
            "Wrestling": {
                "Wild Punch": (6, 10),
                "Wild Kick": (6, 10),
                "Slam": (6, 8),
                "Grapple": (5, 7),
                "Takedown": (5, 7),
                "Suplex": (6, 8),
                "Arm Drag": (4, 6),
                "Double Leg": (6, 8),
                "Single Leg": (5, 7),
                "Neck Crank": (5, 7),
                "Leg Lock": (6, 8),
                "Body Slam": (6, 8),
                "Hip Toss": (5, 7),
                "Bear Hug": (5, 7),
                "Headlock": (4, 6),
                "Piledriver": (7, 9),
                "Powerbomb": (7, 9),
                "Backbreaker": (6, 8),
                "Boston Crab": (6, 8),
                "Camel Clutch": (6, 8),
                "Clothesline": (6, 8),
                "Spinebuster": (7, 9),
                "Gorilla Press": (6, 8),
                "Schoolboy Rollup": (4, 6),
                "Fireman's Carry": (5, 7),
                "Gutwrench Suplex": (6, 8),
                "Full Nelson": (5, 7),
                "Dragon Screw": (5, 7),
                "Ankle Pick": (5, 7),
                "Cradle": (4, 6),
                "Rolling Thunder": (6, 8),
                "Tilt-a-Whirl Slam": (6, 8),
                "Atomic Drop": (5, 7),
                "Stalling Suplex": (6, 8)
            },
            "Krav-Maga": {
                "Palm Strike": (6, 8),
                "Low Kick": (5, 7),
                "Knee Strike": (5, 7),
                "Gouge": (9, 10),
                "Backhand": (5, 7),
                "Finger Strike": (5, 7),
                "Headbutt": (5, 7),
                "Short Elbow": (4, 6),
                "Hammerfist": (7, 8),
                "Inside Knee": (6, 8),
                "Elbow": (6, 8),
                "High Knee": (6, 8),
                "Soccer Kick": (7, 9),
                "Forearm Strike": (5, 7),
                "Side Elbow": (6, 8),
                "Chop": (5, 7),
                "Spinning Elbow": (6, 8),
                "Uppercut": (6, 8),
                "Stomp": (5, 7),
                "Claw Strike": (5, 7),
                "Overhand Punch": (6, 8),
                "Spinning Backfist": (6, 8),
                "Short Kick": (5, 7),
                "Double Palm Strike": (7, 9),
                "Jumping Knee": (7, 9),
                "Reverse Hammerfist": (7, 8),
                "Stabbing Thrust": (8, 9),
                "Side Kick": (6, 8),
                "Hook": (5, 7),
                "Roundhouse Kick": (6, 8),
                "Vertical Punch": (6, 8),
                "Spinning Kick": (7, 9),
                "Disarm Attack": (7, 8)
            },
            "Capoeira": {
                "Sweep": (5, 7),
                "Cartwheel": (4, 6),
                "Headbutt": (5, 7),
                "Spinning Kick": (6, 8),
                "Elbow Strike": (6, 8),
                "Spinning Elbow": (6, 8),
                "Knee Strike": (5, 7),
                "Handstand": (4, 6),
                "Backflip": (6, 8),
                "Front Kick": (5, 7),
                "Roundhouse Kick": (6, 10),
                "Axe Kick": (6, 8),
                "Au Batido": (5, 7),
                "Meia Lua de Compasso": (6, 8),
                "Queixada": (6, 8),
                "Martelo": (5, 7),
                "Armada": (6, 8),
                "Rasteira": (5, 7),
                "Ponteira": (5, 7),
                "Negativa": (4, 6),
                "Cocorinha": (4, 6),
                "Meia Lua de Frente": (5, 7),
                "Parafuso": (6, 9),
                "Giro de Mao": (6, 8),
                "Escorpião": (6, 8),
                "Queda de Rins": (5, 7),
                "Chapa": (6, 8),
                "Pisao": (5, 7),
                "Meia Lua Reversao": (6, 8),
                "S-Dobrado": (6, 9),
                "Joelhada": (5, 7),
                "Tesoura de Frente": (6, 8),
                "Chibata": (5, 7)
            },
            "Sambo": {
                "Throw": (5, 7),
                "Lock": (4, 6),
                "Sweep": (4, 6),
                "Chokehold": (5, 7),
                "Ankle Lock": (6, 8),
                "Knee Bar": (6, 8),
                "Armbar": (6, 8),
                "Leg Lock": (6, 8),
                "Wrist Lock": (5, 7),
                "Shoulder Lock": (5, 7),
                "Neck Crank": (6, 8),
                "Reverse Armbar": (6, 8),
                "Reverse Leg Lock": (6, 8)
            },
            "Kickboxing":  {
                "Kick": (6, 8),
                "Straight Punch": (5, 7),
                "Hook": (5, 7),
                "Knee Strike": (5, 7),
                "Spinning Backfist": (6, 8),
                "Low Kick": (5, 7),
                "High Kick": (6, 8),
                "Body Kick": (5, 7),
                "Hook Kick": (6, 8),
                "Roundhouse Kick": (6, 8),
                "Axe Kick": (6, 8),
                "Side Kick": (5, 7),
                "Crescent Kick": (6, 8),
                "Reverse Roundhouse": (6, 8),
                "Reverse Side Kick": (6, 8),
                "Front Kick": (5, 7),
                "Jab": (4, 6),
                "Cross": (5, 7),
                "Uppercut": (6, 8),
                "Overhand Punch": (6, 8),
                "Elbow Strike": (6, 8),
                "Jumping Knee": (7, 9),
                "Spinning Heel Kick": (7, 9),
                "Teep Kick": (5, 7),
                "Flying Knee": (7, 9),
                "Back Kick": (6, 8),
                "Jumping Front Kick": (6, 8),
                "Jumping Roundhouse Kick": (7, 9),
                "Spinning Hook Kick": (7, 9),
                "Double Jab": (5, 7),
                "Cross Hook Combo": (6, 8),
                "Elbow-Knee Combo": (7, 9)
        },
            "MMA": {
                "Left Straight": (6, 8),
                "Right Straight": (6, 8),
                "Hook": (5, 7),
                "Left Uppercut": (6, 8),
                "Right Uppercut": (6, 8),
                "Superman Punch": (7, 9),
                "Flying Knee": (7, 9),
                "Kick": (6, 8),
                "Submission": (5, 8),
                "Ground and Pound": (7, 9),
                "Rear Naked Choke": (9, 10),
                "Spinning Back Fist": (6, 8),
                "Elbow Strike": (6, 8),
                "Knee": (5, 7),
                "Body Slam": (6, 8),
                "Short Kick": (5, 7),
                "Switch Kick": (8, 10),
                "Triangle Choke": (8, 10),
                "Armbar": (7, 9),
                "Guillotine Choke": (7, 9),
                "Spinning Heel Kick": (8, 10),
                "Takedown": (5, 7),
                "Ankle Lock": (6, 8),
                "Kimura": (6, 8),
                "D'Arce Choke": (8, 10),
                "Flying Armbar": (9, 10),
                "Jumping Knee": (7, 9),
                "Standing Elbow": (6, 8),
                "Short Inside Knee": (5, 7),
                "Spinning Back Kick": (7, 9),
                "High Kick": (7, 9)
            },
            "Brazilian Jiu-Jitsu": {
                "Armbar": (6, 8),
                "Triangle Choke": (5, 7),
                "Kimura": (6, 8),
                "Omoplata": (6, 8),
                "Rear Naked Choke": (6, 8),
                "Sweep": (4, 6),
                "Guard Pass": (5, 7),
                "Mount": (6, 8),
                "Back Take": (6, 8),
                "Darce Choke": (7, 9),
                "Guillotine": (7, 9),
                "Arm Triangle": (6, 8),
                "Heel Hook": (7, 9),
                "Toe Hold": (7, 9),
                "Knee Bar": (7, 9),
                "Straight Ankle Lock": (6, 8),
                "Wrist Lock": (5, 7),
                "Crucifix": (6, 8),
                "Loop Choke": (7, 9),
                "Bow and Arrow Choke": (7, 9),
                "Clock Choke": (6, 8),
                "Paper Cutter Choke": (7, 9),
                "Bread Cutter Choke": (8, 10)
            }
        }

BODY_PARTS = [
    "head", "chest", "left arm", "right arm", "nose", "neck", "left ear", "right ear",
    "teeth", "left leg", "right leg", "right foot", "left foot", "liver", "kidneys",
    "spine", "clavical", "left hip", "right hip", "left knee", "right knee", "solar plexus",
    "cranium", "kisser", "chin", "left shoulder", "right shoulder", "ass", "crotch", "spine", "ribs", "spinal column",
    "left ankle", "right ankle", "jaw", "left eye", "right eye", "stomach", "temple", "forehead", "mid-section","stomach",
    "throat", "ribcage", "butt"
]

GRAPPLE_ACTIONS = [
    "completes", "nails", "executes", "finishes", "performs", "grabs", "attains", "pulls off", "applies", "transitions to", "forces"]

GRAPPLE_KEYWORDS = [
    "Choke", "Mount", "Triangle", "Kimura", "Omoplata", "Crucifix", "Guillotine", "Lock", "Bar", "Hold", "Submission", "Crank", "Takedown", "Suplex", "Slam", "Throw", "Drag", "Take", "Redirect", "Chokehold", "Single Leg", "Double Leg", "Hug", "Toss", "Fireman", "Piledriver", "Full Nelson", "Cradle", "Clinch"
]

STRIKE_ACTIONS = [
    "throws", "slams", "nails", "whacks", "connects", "rips", "thuds", "crushes", "snaps", "smashes", 
    "pounds", "cracks", "hits", "drives", "lands", "bashes", "clobbers", "wallops", "hammers",
    "strikes", "belts", "mashes", "pummels", "slugs", "batters", "blasts", "bludgeons", "thumps", "thwacks",
    "wacks", "whams", "socks", "smacks", "beats", "whomps", "whips", "thwumps", "clangs", "claps", "donks"
]

CRITICAL_MESSAGES = [
    "Channeling the power of the Dim Mak strike,",
    "Harnessing the technique bestowed upon them by the Black Dragon Fighting Society,",
    "Channeling the Grand Master Ashida Kim,",
    "Summoning the power of Count Dante,",
    "Channeling the power of the Black Dragon,",
    "Feeling the power of the Black Cobra,",
    "Feeling the power of the Black Dragon,",
    "Harnessing the strength of Master Yoshi,",
    "Unleashing the Chi energy of The Red Tiger,",
    "Summoning the spirit of The White Crane,",
    "Calling upon the secrets of the Shadow Serpent,",
    "Harnessing the precision of Master Liu Kang,",
    "Channeling the ferocity of the Jade Dragon,",
    "Invoking the techniques of the Phoenix Warrior,",
    "Invoking the force of the Midnight Panther,",
    "Channeling the might of the Storm Dragon,",
    "Drawing from the power of the Fire Phoenix,",
    "Summoning the power of the Tiger's Claw,",
    "Drawing from the legendary moves of the Tai Chi Tortoise,",
    "Unleashing the might of the Combat Corgi,",
    "Unleashing the fury of the Mighty Mongoose,",
    "Drawing from the legendary moves of the Tai Chi Terrier,",
    "Invoking the techniques of Steven Segal,",
    "Recalling the power of Master Ti Ni Peen,",
    "Drawing from the legendary moves of Yung Ho,",
    "Channeling the power of Grand Master Chew Kok,",
    "Unleashing the power of Lo Hung Dong,",
    "Lifting the power of Phat Ho,",
    "Invoking the power of Master Ti Ni Peen,",
    "Calling upon the power of the Gokkun Gorilla,",
    "Unleashing the power of the Bukkake Beast,",
    "Channeling the spirit of Bruce Lee,",
    "Invoking the techniques of Frank Dux,",
    "Summoning the strength of Chuck Norris,",
    "Harnessing the power of Jet Li,",
    "Drawing from the precision of Jackie Chan,",
    "Channeling the ferocity of Anderson Silva,",
    "Summoning the power of Royce Gracie,",
    "Invoking the moves of Ken Shamrock,",
    "Harnessing the strength of Bas Rutten,",
    "Channeling the techniques of Georges St-Pierre,",
    "Summoning the spirit of Randy Couture,",
    "Drawing from the power of Fedor Emelianenko,",
    "Channeling the energy of Lyoto Machida,",
    "Invoking the precision of Conor McGregor,",
    "Summoning the strength of Ronda Rousey,",
    "Harnessing the power of Demetrious Johnson,",
    "Drawing from the techniques of Jon Jones,",
    "Channeling the spirit of Holly Holm,",
    "Summoning the moves of Dan Severn,",
    "Invoking the force of Mark Coleman,",
    "Harnessing the power of Kazushi Sakuraba,",
    "Channeling the ferocity of Wanderlei Silva,",
    "Summoning the techniques of B.J. Penn,",
    "Drawing from the strength of Matt Hughes,",
    "Channeling the energy of Tito Ortiz,",
    "Invoking the precision of Anderson Silva,",
    "Summoning the spirit of Vitor Belfort,",
    "Harnessing the techniques of Mirko Cro Cop,",
    "Channeling the strength of Ubereem,",
    "Drawing from the power of Sea Level Cain,",
    "Invoking the moves of Daniel Cormier,",
    "Summoning the energy of Israel Adesanya,",
    "Harnessing the precision of Amanda Nunes,",
    "Channeling the strength of Valentina Shevchenko,",
    "Summoning the techniques of Khabib Nurmagomedov,",
    "Calling upon the wisdom of the Ancient Turtle Master,",
    "Harnessing the speed of the Cheetah Warrior,",
    "Channeling the agility of the Silver Fox,",
    "Summoning the power of the Mighty Platypus,",
    "Drawing from the legendary moves of the Ninja Squirrel,",
    "Unleashing the spirit of the Golden Unicorn,",
    "Invoking the energy of the Cosmic Panda,",
    "Harnessing the stealth of the Shadow Gecko,",
    "Channeling the wisdom of the Wise Old Owl,",
    "Summoning the strength of the Fire Salamander,",
    "Drawing from the ancient techniques of the Mystic Sloth,",
    "Invoking the power of the Thunder Dolphin,",
    "Unleashing the force of the Electric Eel,",
    "Harnessing the swiftness of the Lightning Hare,",
    "Channeling the might of the Stone Rhino,",
    "Summoning the energy of the Phantom Mantis,",
    "Drawing from the legendary skills of the Crimson Cobra,",
    "Invoking the ferocity of the Blizzard Bear,",
    "Harnessing the technique of the Wind Falcon,",
    "Channeling the strength of the Iron Giraffe,",
    "Summoning the power of the Tornado Tortoise,",
    "Drawing from the ancient art of the Silent Llama,",
    "Unleashing the might of the Emerald Iguana,",
    "Invoking the energy of the Solar Lion,",
    "Harnessing the precision of the Rainbow Macaw,",
    "Channeling the force of the Ice Jaguar,",
    "Summoning the spirit of the Thunder Wolf,",
    "Drawing from the moves of the Stellar Parrot,",
    "Invoking the power of the Hurricane Hawk,",
    "Unleashing the fury of the Tempest Tiger,",
    "Harnessing the agility of the Moon Rabbit,",
    "Channeling the might of the Mountain Gorilla,",
    "Summoning the strength of the Vortex Viper,",
    "Drawing from the legendary moves of the Sky Serpent,",
    "Invoking the force of the Shadow Shark,",
    "Unleashing the spirit of the Golden Phoenix,"
]


CRITICAL_RESULTS = {
    "{defender} is gasping for air!": "Punctured Lung",
    "{defender} suffers a broken nose!": "Broken Nose",
    "{defender} has a shattered rib!": "Shattered Rib",
    "{defender} winces in pain from a dislocated left shoulder!": "Dislocated Left Shoulder",
    "{defender} winces in pain from a dislocated right shoulder!": "Dislocated Right Shoulder",
    "{defender} holds their broken jaw!": "Broken Jaw",
    "{defender} appears dazed from a concussion!": "Concussion",
    "{defender} struggles with a broken right leg!": "Broken Right Leg",
    "{defender} struggles with a broken left leg!": "Broken Left Leg",
    "{defender} clutches their broken right arm!": "Broken Right Arm",
    "{defender} clutches their broken left arm!": "Broken Left Arm",
    "{defender}'s right arm is tweaked!": "Fractured Right Arm",
    "{defender}'s left arm is tweaked!": "Fractured Left Arm",
    "{defender}'s right leg is tweaked! Ouch!": "Fractured Right Leg",
    "{defender}'s left leg is tweaked! Ouch!": "Fractured Left Leg",
    "{defender} winces from a broken left collarbone!": "Broken Left Collarbone",
    "{defender} winces from a broken right collarbone!": "Broken Right Collarbone",
    "{defender} struggles with a broken left wrist!": "Broken Left Wrist",
    "{defender} struggles with a broken right wrist!": "Broken Right Wrist",
    "{defender} stumbles from a broken left ankle!": "Broken Ankle",
    "{defender} stumbles from a broken right ankle!": "Broken Ankle",
    "{defender} grimaces with a broken finger!": "Broken Finger",
    "{defender} grimaces with a broken toe!": "Broken Toe",
    "{defender} clutches their broken rib!": "Broken Rib",
    "{defender} is in pain from a broken shin!": "Broken Shin",
    "{defender} limps with a broken thigh!": "Broken Thigh",
    "{defender} cries out from a broken kneecap!": "Broken Kneecap",
    "{defender} struggles to stand with a broken left foot!": "Broken Left Foot",
    "{defender} struggles to stand with a broken right foot!": "Broken Right Foot",
    "{defender} holds their broken hand!": "Broken Hand",
    "{defender} has a cut over their eye!": "Cut Eye",
    "{defender} is sporting a black eye!": "Black Eye",
    "{defender} has a bloody nose!": "Bloody Nose",
    "{defender}'s nose is smashed and bloody!": "Broken Nose",
    "{defender} has a bloody lip!": "Cut Lip",
    "{defender} has a bloody ear!": "Damaged Eardrum",
    "{defender} spits blood from a cut mouth!": "Cut Mouth",
    "{defender} has a bloody forehead!": "Cut Forehead",
    "{defender} wipes blood from their cheek!": "Bloody Cheek",
    "{defender} suffers a detached left retina!": "Detached Left Retina",
    "{defender} suffers a detached right retina!": "Detached Right Retina",
    "{defender}'s left shoulder is in agony and appears broken!": "Broken Left Shoulder",
    "{defender}'s right shoulder is in agony and appears broken!": "Broken Right Shoulder",
    "{defender} has broken teeth!": "Broken Teeth",
    "{defender} is left with a fractured skull!": "Fractured Skull",
    "{defender} is left with a collapsed lung!": "Collapsed Lung",
    "{defender} is experiencing internal bleeding!": "Internal Bleeding",
    "{defender} is left with a ruptured spleen!": "Ruptured Spleen",
    "{defender} is dealing with a torn muscle!": "Torn Muscle",
    "{defender} is in agony from a dislocated knee!": "Dislocated Knee",
    "{defender} is suffering from a fractured pelvis!": "Fractured Pelvis",
    "{defender} is left with a split lip!": "Split Lip",
    "{defender} is clutching a cracked rib!": "Cracked Rib",
    "{defender} is dealing with a sprained wrist!": "Sprained Wrist",
    "{defender} is limping with a sprained ankle!": "Sprained Ankle",
    "{defender} has a deep cut on the arm!": "Deep Arm Cut",
    "{defender} has a deep cut on the leg!": "Deep Leg Cut",
    "{defender} is suffering from a torn ligament!": "Torn Ligament",
    "{defender} is wincing from a bruised rib!": "Bruised Rib",
    "{defender} is suffering from a bruised kidney!": "Bruised Kidney",
    "{defender} is left with a broken elbow!": "Broken Elbow",
    "{defender} is left with a broken kneecap!": "Broken Kneecap",
    "{defender} is suffering from a ruptured eardrum!": "Ruptured Eardrum",
    "{defender} has a cracked skull!": "Cracked Skull",
}

INJURY_TREATMENT_COST = {
    "Punctured Lung": 8300,
    "Broken Nose": 1150,
    "Shattered Rib": 6250,
    "Dislocated Left Shoulder": 2180,
    "Dislocated Right Shoulder": 2180,
    "Fractured Right Arm": 3100,
    "Fractured Left Arm": 3100,
    "Fractured Left Leg": 3100,
    "Fractured Right Leg": 3100,
    "Broken Jaw": 4220,
    "Concussion": 1300,
    "Broken Right Leg": 5270,
    "Broken Left Leg": 5270,
    "Broken Right Arm": 3240,
    "Broken Left Arm": 3240,
    "Broken Left Collarbone": 3260,
    "Broken Right Collarbone": 3260,
    "Broken Left Wrist": 1130,
    "Broken Right Wrist": 1130,
    "Broken Ankle": 1140,
    "Broken Finger": 1150,
    "Broken Toe": 1140,
    "Broken Rib": 1250,
    "Broken Shin": 1120,
    "Broken Thigh": 1230,
    "Broken Kneecap": 1210,
    "Broken Left Foot": 1160,
    "Broken Right Foot": 1160,
    "Broken Hand": 1190,
    "Cut Eye": 110,
    "Black Eye": 180,
    "Bloody Nose": 160,
    "Cut Lip": 170,
    "Damaged Eardrum": 1190,
    "Cut Mouth": 100,
    "Cut Forehead": 130,
    "Bloody Cheek": 120,
    "Detached Left Retina": 4100,
    "Detached Right Retina": 4100,
    "Broken Left Shoulder": 1180,
    "Broken Right Shoulder": 1180,
    "Broken Teeth": 1300,
    "Fractured Skull": 5400,
    "Collapsed Lung": 5350,
    "Internal Bleeding": 5500,
    "Ruptured Spleen": 10450,
    "Torn Muscle": 6200,
    "Dislocated Knee": 4200,
    "Fractured Pelvis": 10400,
    "Split Lip": 170,
    "Cracked Rib": 6230,
    "Sprained Wrist": 1100,
    "Sprained Ankle": 1100,
    "Deep Arm Cut": 1150,
    "Deep Leg Cut": 1150,
    "Torn Ligament": 1300,
    "Bruised Rib": 1180,
    "Bruised Kidney": 5120,
    "Broken Elbow": 4220,
    "Ruptured Eardrum": 3100,
    "Cracked Skull": 5400,
}




KO_MESSAGES = [
    "{loser} got knocked the fuck out!",
    "{loser} got KO'd!",
    "{loser} is out cold!",
    "{loser} got knocked out!",
    "{loser} is seeing glimpses of the afterlife!",
    "{loser} is unresponsive!",
    "{loser} is out like a light!",
    "{loser} got flattened!",
    "{loser} got their lights turned off!",
    "{loser} is unconscious!",
    "{loser} got put to sleep!",
    "{loser} got sent to the shadow realm!",
    "{loser} got laid out!",
    "{loser} is out of commission!",
    "{loser} got knocked senseless!",
    "{loser} got sent to dreamland!",
    "{loser} got sent to sleep!",
    "{loser} is out on the canvas!",
    "{loser} got knocked stiff!",
    "{loser} got dropped hard!",
    "{loser} is out on the floor!",
    "{loser} got knocked into next week!",
    "{loser} is out like a switch!",
    "{loser} is sleeping on the job!",
    "{loser} got his bell rung!",
    "{loser} is out and not moving!",
    "{loser} got his clock cleaned!",
    "{loser} is down and out!",
    "{loser} got shut off!",
    "{loser} got their lights dimmed!",
    "{loser} is down for the count!",
    "{loser} is out for the night!",
    "{loser} got put on ice!",
    "{loser} got iced!",
    "{loser} got sparked out!",
    "{loser} got sent to the land of nod!",
    "{loser} got KO'd in spectacular fashion!",
    "{loser} got knocked into oblivion!",
    "{loser} is flat on his back!",
    "{loser} got taken out!",
    "{loser} got sent to the mat!",
    "{loser} got blown away!",
    "{loser} got shut down!",
    "{loser} is out cold on the mat!",
    "{loser} is out cold on the floor!",
    "{loser} got his lights shut off!",
    "{loser} is down and out cold!",
    "{loser} got sent to the canvas!",
    "{loser} got obliterated!",
    "{loser} got taken to the cleaners!",
    "{loser} is out cold, no response!",
    "{loser} got KO'd hard!",
    "{loser} got blasted out!",
    "{loser} got starched!",
    "{loser} got sent to the astral plane!",
    "{loser} got sent to sleep town!",
    "{loser} got laid out cold!",
    "{loser} got knocked out cold!",
    "{loser} got stopped in his tracks!",
    "{loser} is out like a light bulb!",
    "{loser} got shut down completely!",
    "{loser} is out like a rock!",
    "{loser} got sent to nap time!",
    "{loser} is out like a log!",
    "{loser} got their power cut off!",
    "{loser} is seeing stars!",
    "{loser} got put out cold!",
    "{loser} got switched off!",
    "{loser} is out cold on the ground!",
    "{loser} got hammered!",
    "{loser} got his world rocked!",
    "{loser} got laid out flat!",
    "{loser} got clobbered!",
    "{loser} got turned off like a switch!",
    "{loser} got sent to the floor!",
    "That's a huge knockout, {loser} is out!",
    "It's lights out for {loser}!",
    "What a knockout, {loser} is done!",
    "An incredible KO, {loser} is out!",
    "The lights just went out for {loser}!",
    "The fight is over, {loser} is out cold!",
    "A devastating punch, {loser} is down!",
    "Down goes {loser}, out cold!",
    "A brutal KO, {loser} is out!",
    "The referee could count to 100, {loser} is out!",
    "A massive knockout, {loser} is on the floor!",
    "No need for a count, {loser} is done!",
    "It's all over, {loser} got KO'd!",
    "A thunderous KO, {loser} is out!",
    "The fight ends with {loser} unconscious!",
    "A crushing blow, {loser} is out!",
    "It's a knockout, {loser} is out of it!",
    "The end comes swiftly for {loser}!",
    "A spectacular KO, {loser} is done!",
    "A clean knockout, {loser} is out cold!",
    "A powerful strike, {loser} is out!",
    "The final blow, {loser} is unconscious!",
    "A knockout punch, {loser} is out!",
    "The bout ends with {loser} down!",
    "A knockout finish, {loser} is out!",
    "A decisive KO, {loser} is out!",
    "A perfect punch, {loser} is out cold!",
    "The fight ends, {loser} is knocked out!",
    "A knockout victory, {loser} is down!",
    "The final bell, {loser} is out cold!",
    "A dramatic KO, {loser} is out!",
    "A huge knockout, {loser} is done!",
    "A knockout blow, {loser} is out!",
    "It's a KO, {loser} is down and out!",
    "A finishing punch, {loser} is out!",
    "The end comes for {loser}, knocked out!",
    "With a thunderous punch, {loser} is down!",
    "A perfectly timed strike, {loser} is out!",
    "A devastating right hand, {loser} is on the canvas!",
    "A powerful uppercut, and {loser} is out cold!",
    "A left hook sends {loser} to the mat, unconscious!",
    "A massive right hand, and {loser} is out!",
    "A crushing blow, {loser} is out cold!",
    "A knockout punch, and {loser} is down for the count!",
    "A swift right hand, {loser} is out!",
    "A clean shot puts {loser} to sleep!",
    "A brutal knockout, {loser} is done!",
    "A powerful strike, and {loser} is out!",
    "A crushing uppercut, {loser} is out cold!",
    "A devastating blow, {loser} is down and out!",
    "A knockout punch, and {loser} is out cold!",
    "A perfectly placed punch, and {loser} is out!",
    "A brutal right hand, and {loser} is out!",
    "A devastating hook, {loser} is on the mat!",
    "A knockout strike, {loser} is out cold!",
    "A powerful blow, {loser} is out for the count!",
    "A crushing punch, and {loser} is out cold!",
    "A clean knockout, and {loser} is down!",
    "A powerful right, {loser} is out cold!",
    "A brutal punch, and {loser} is down and out!",
    "A knockout shot, {loser} is out cold!",
    "A devastating right, {loser} is down!",
    "A thunderous punch, {loser} is out cold!"
]


TKO_MESSAGES = [
    "{loser} is out on his feet!",
    "{loser} is hurt!",
    "{loser} is just trying to survive!",
    "{loser} is doing the skanky leg!",
    "{loser} is in survival mode!",
    "{loser} is getting hurt in there!",
    "{loser} is wobbled!",
    "{loser} is wobbling!",
    "{loser} is in dire straits!",
    "{loser} is in deep trouble!",
    "{loser} is struggling to stay up!",
    "{loser} is struggling to stay on their feet!",
    "{loser} is barely standing!",
    "{loser} is on shaky legs!",
    "{loser} is on rubbery legs!",
    "{loser} is in big trouble!",
    "{loser} is defenseless!",
    "{loser} is not fighting back!",
    "{loser} is eating too many shots!",
    "{loser} is taking heavy shots!",
    "{loser} is out of it!",
    "{loser} is losing balance!",
    "{loser} is on the verge of collapse!",
    "{loser} is about to go down!",
    "{loser} is looking very vulnerable!",
    "{loser} is getting pounded!",
    "{loser} is on unsteady legs!",
    "{loser} is getting overwhelmed!",
    "{loser} is in serious trouble!",
    "{loser} is dazed and confused!",
    "{loser} is getting rocked!",
    "{loser} is in no condition to continue!",
    "{loser} is taking too much punishment!",
    "{loser} is barely holding on!",
    "{loser} is on the ropes!",
    "{loser} is getting battered!",
    "{loser} is on the brink of defeat!",
    "{loser} is getting demolished!",
    "{loser} is in desperate trouble!",
    "{loser} is getting mauled!",
    "{loser} is one punch away from going down!",
    "{loser} is taking a beating!",
    "{loser} is being dominated!",
    "{loser} is on the edge of a knockout!",
    "{loser} is in a bad way!",
    "{loser} is teetering!",
    "{loser} is about to be stopped!",
    "{loser} is hanging by a thread!",
    "{loser} is close to being finished!",
    "{loser} is on their last legs!",
    "{loser} is on the brink!",
    "{loser} is getting tagged!",
    "{loser} is getting smashed!",
    "{loser} is on the verge!",
    "{loser} is reeling!",
    "{loser} is defenseless against the assault!",
    "{loser} is taking unanswered shots!",
    "{loser} is barely able to defend themselves!",
    "{loser} is out on his feet, taking punishment!",
    "{loser} is struggling to maintain consciousness!",
    "{loser} is in danger of being knocked out!",
    "{loser} is on the verge of getting knocked down!",
    "{loser} is in bad shape!",
    "{loser} is looking worse for wear!",
    "{loser} is taking too many unanswered punches!",
    "{loser} is in no shape to defend!",
    "{loser} is in bad trouble!",
    "{loser} is in serious danger!",
    "{loser} is in real peril!",
    "{loser} is absorbing a lot of punishment!",
    "{loser} is fading fast!",
    "{loser} is nearly out on his feet!",
    "{loser} is getting pummeled!",
    "{loser} is stumbling!",
    "{loser} is on the verge of being overwhelmed!",
    "{loser} is facing imminent defeat!",
    "{loser} is close to going down!",
    "{loser} is unable to defend themselves!",
    "{loser} is in retreat!",
    "{loser} is being outclassed!",
    "{loser} is in survival mode, barely hanging on!",
    "{loser} is struggling to stay conscious!",
    "{loser} is being overwhelmed by the onslaught!",
    "{loser} is taking a lot of damage!",
    "{loser} is getting manhandled!",
    "{loser} is about to be overwhelmed!",
    "{loser} is barely hanging in there!",
    "{loser} is close to being overwhelmed!",
    "{loser} is taking heavy fire!",
    "{loser} is almost out on his feet!",
    "{loser} is getting pummeled by the shots!",
    "It's clear that {loser} is out on his feet!",
    "Hurt and struggling, {loser} is just trying to survive!",
    "Doing the skanky leg, {loser} is in survival mode!",
    "Getting hurt in there, {loser} is wobbled!",
    "In dire straits, {loser} is in deep trouble!",
    "Struggling to stay up, {loser} is barely standing!",
    "Defenseless and not fighting back, {loser} is eating too many shots!",
    "Losing balance, {loser} is on the verge of collapse!",
    "Looking very vulnerable, {loser} is getting pounded!",
    "Getting overwhelmed, {loser} is in serious trouble!",
    "Dazed and confused, {loser} is in no condition to continue!",
    "Barely holding on, {loser} is on the ropes!",
    "On the brink of defeat, {loser} is getting demolished!",
    "In desperate trouble, {loser} is one punch away from going down!",
    "Taking a beating, {loser} is being dominated!",
    "On the edge of a knockout, {loser} is teetering!",
    "About to be stopped, {loser} is hanging by a thread!",
    "Close to being finished, {loser} is on their last legs!",
    "Getting tagged, {loser} is on the verge!",
    "Defenseless against the assault, {loser} is taking unanswered shots!",
    "Barely able to defend themselves, {loser} is out on his feet, taking punishment!",
    "In danger of being knocked out, {loser} is on the verge of getting knocked down!",
    "Taking too many unanswered punches, {loser} is in bad trouble!",
    "In serious danger, {loser} is absorbing a lot of punishment!",
    "Nearly out on his feet, {loser} is getting pummeled!",
    "On the verge of being overwhelmed, {loser} is facing imminent defeat!",
    "Unable to defend themselves, {loser} is in retreat!",
    "Being outclassed, {loser} is in survival mode, barely hanging on!",
    "Taking a lot of damage, {loser} is getting manhandled!",
    "About to be overwhelmed, {loser} is barely hanging in there!",
    "Taking heavy fire, {loser} is almost out on his feet!",
    "Pummeled by the shots, {loser} is on the brink!"
    ]


SUBMISSION_MESSAGES = [
    "{loser} tapped!",
    "{loser} wants out, they tapped!",
    "There's the tap, {loser} has had enough!",
    "{loser} tapped like a bitch!"
]

FIGHT_RESULT_LONG = {
    "UD": "Unanimous Decision",
    "SD": "Split Decision",
    "KO": "Knock Out",
    "TKO": "Technical Knock Out"
}

REFEREE_STOPS = [
    "Herb Dean has seen enough!",
    "The referee has seen enough!",
    "The referee stops it!",
    "Yves Lavigne is thinking of stopping it, it's over!",
    "Big John steps in!",
    "The ref is stopping this!",
    "Mario Yamasaki is trying to stop it!",
    "The ref is about to call this one!",
    "The ref has called a halt to the fight!",
    "The referee waves it off!",
    "The ref signals the end!",
    "Yves Lavigne has seen enough, he stops it!",
    "Big John puts an end to it!",
    "The ref jumps in, it's over!",
    "Big John calls a stop to the action!",
    "Herb Dean has seen enough, it's over folks!",
    "The ref calls it, fight's over!",
    "Referee Josh Rosenthal steps in!",
    "Herb Dean dives between them!",
    "The fight is stopped by the referee!",
    "The referee steps in, it's all over!",
    "The referee ends the contest!",
    "The ref intervenes, it's done!",
    "The referee calls a stop to the bout!",
    "Referee Mike Beltran steps in, it's over!",
    "The ref calls it off!",
    "The referee steps in to stop the fight!",
    "The fight is waved off by the ref!",
    "The referee puts an end to the match!",
    "Referee Herb Dean steps in, it's all over!",
    "The referee stops the fight!",
    "The referee steps between the fighters!",
    "The ref signals the end of the bout!",
    "The referee halts the contest!",
    "The ref steps in to save the fighter!",
    "The fight is stopped by the referee's intervention!",
    "The referee puts a halt to the fight!",
    "The ref steps in, it's over!",
    "Referee Herb Dean has seen enough!",
    "The ref jumps in to stop the punishment!",
    "The ref steps in to protect the fighter!",
    "The referee has seen enough punishment!",
    "The ref waves off the contest!",
    "Referee steps in, fight's over!",
    "The ref dives in to save the fighter!",
    "The referee decides to stop the fight!",
    "The ref puts an end to the beating!",
    "The referee steps in, fight ends!",
    "The ref calls a halt to the action!",
    "Referee intervenes, fight's over!",
    "The ref calls the fight!",
    "The referee jumps in, it's done!",
    "The referee steps in, it's over folks!",
    "Referee halts the fight!",
    "The referee stops the bout!",
    "The referee signals the end!",
    "The ref steps in, it's all over!",
    "Referee waves it off, fight's done!",
    "The referee calls an end to the contest!",
    "The ref steps in, it's over now!",
    "The referee ends it, it's all over!",
    "Dan Miragliotta has seen enough, he stops it!",
    "Keith Peterson steps in, it's all over!",
    "Marc Goddard calls a stop to the fight!",
    "Jason Herzog steps in to stop the bout!",
    "Referee Dan Miragliotta stops the contest!",
    "Keith Peterson waves off the fight!",
    "Marc Goddard has seen enough, it's over!",
    "Jason Herzog puts an end to the action!",
    "Herb Dean steps in, it's all over!",
    "Dan Miragliotta stops the fight!",
    "Keith Peterson jumps in, it's over!",
    "Marc Goddard ends the bout!",
    "Jason Herzog signals the end of the fight!",
    "Referee Dan Miragliotta intervenes, it's done!",
    "Keith Peterson calls it off!",
    "Marc Goddard dives in, it's over!",
    "Jason Herzog halts the contest!",
    "Referee Herb Dean steps in, fight's over!",
    "Dan Miragliotta waves it off!",
    "Keith Peterson stops the action!",
    "Marc Goddard steps in, fight's done!",
    "Jason Herzog calls the fight!",
    "Herb Dean stops the contest!",
    "Dan Miragliotta steps in, it's over!",
    "Keith Peterson intervenes, it's done!",
    "Marc Goddard calls a halt to the fight!",
    "Jason Herzog waves off the bout!",
    "Referee Herb Dean dives in to stop the fight!",
    "Dan Miragliotta puts an end to the match!",
    "Keith Peterson signals the end of the fight!",
    "Marc Goddard steps in, it's all over!",
    "Jason Herzog stops the beating!",
    "Herb Dean halts the bout!",
    "Dan Miragliotta calls it, fight's over!",
    "Keith Peterson dives in, it's over!",
    "Marc Goddard waves it off, fight's done!",
    "Jason Herzog ends the contest!",
    "Referee Herb Dean puts an end to the fight!",
    "Dan Miragliotta steps in, it's done!",
    "Keith Peterson jumps in, it's over folks!",
    "Marc Goddard stops the punishment!",
    "Jason Herzog calls a halt to the action!",
    "Referee Herb Dean signals the end!",
    "Dan Miragliotta steps in to save the fighter!",
    "Keith Peterson calls it, fight's over!",
    "Marc Goddard intervenes, it's done!",
    "Jason Herzog steps in, it's over now!"
]


TKO_VICTOR_MESSAGE = ["bringing the pain!",
    "ended that brutally!",
    "is a monster!",
    "is a beast!",
    "had bad intentions!",
    "showed some serious power",
    "sends a message to their challengers",
    "made a statement!",
    "was relentless!",
    "was a force of nature!",
    "overwhelmed their opponent!",
    "brought the hammer down!",
    "brought the pain!",
    "proved their might!",
    "is unstoppable!",
    "showed no mercy!",
    "struck with precision and power!",
    "proved their dominance!",
    "crushed their foe!",
    "unleashed fury!",
    "showed devastating power!",
    "dominated from start to finish!",
    "was an unstoppable force!",
    "left no doubt!",
    "demolished their opponent!",
    "came out victorious with authority!",
    "was a whirlwind of destruction!",
    "proved their superiority!",
    "left their mark!",
    "took control and never let go!",
    "displayed ruthless efficiency!",
    "showed unmatched power!",
    "was a juggernaut!",
    "steamrolled their competition!",
    "obliterated their adversary!",
    "put on a clinic!",
    "gave a masterclass in striking!",
    "was an immovable object!",
    "showed killer instinct!",
    "was on a rampage!",
    "destroyed their competition!",
    "put on a dominant performance!",
    "was an absolute wrecking ball!",
    "showed the heart of a champion!",
    "showed relentless aggression!",
    "delivered a flawless victory!",
    "left their opponent in ruins!",
    "asserted their dominance!",
    "demonstrated their superiority!",
    "was a one-person wrecking crew!",
    "came out swinging and didn't stop!",
    "showed incredible ferocity!",
    "proved why they are a top contender!",
    "came out victorious with undeniable power!",
    "displayed unparalleled strength!",
    "laid waste to their opponent!",
    "showed brute force!",
    "delivered a crushing blow!",
    "dominated the fight!",
    "showed supreme confidence!",
    "showed unyielding power!",
    "broke their opponent's will!",
    "showed absolute mastery!",
    "demonstrated unbreakable will!",
    "was a force to be reckoned with!",
    "executed a perfect game plan!",
    "made it look easy!",
    "delivered a powerful performance!",
    "was a storm of power!",
    "gave a stunning performance!",
    "displayed fierce determination!",
    "tore through their opponent!",
    "unleashed a barrage of strikes!",
    "overpowered their adversary!",
    "showed their fighting spirit!",
    "displayed raw power!",
    "delivered a punishing defeat!",
    "was an indomitable force!",
    "showed why they are a champion!",
    "unleashed a flurry of attacks!",
    "showed true grit!",
    "was an unrelenting force!",
    "came out on top with sheer power!",
    "delivered an epic beatdown!",
    "showed no signs of weakness!",
    "put on a spectacular show!",
    "was a relentless machine!",
    "overcame their opponent with ease!",
    "proved to be invincible!",
    "showed their true strength!",
    "executed with precision!",
    "demonstrated superior skill!",
    "showed ruthless efficiency!",
    "delivered a powerful knockout!",
    "was a devastating force!",
    "proved their supremacy!",
    "gave a performance to remember!",
    "showed no mercy!",
    "was a beast in the ring!"
    ]


KO_VICTOR_MESSAGE = [
    "Beat them into a living death!",
    "is an absolute beast!",
    "is an absolute monster!",
    "has some heavy hands!",
    "made a statement!",
    "put him to sleep!",
    "sends a message to their challengers",
    "had bad intentions!",
    "sent him to sleep!",
    "turned out the lights!",
    "delivered a knockout blow!",
    "sent shockwaves through the arena!",
    "brought the hammer down!",
    "dropped them with authority!",
    "left them seeing stars!",
    "is a savage!",
    "put them out with a barrage of power!",
    "unleashed a devastating KO!",
    "showed unbelievable power!",
    "dominated with a crushing finish!",
    "landed a perfect shot!",
    "ended it with a massive blow!",
    "shut down the fight with one strike!",
    "put on a show-stopping performance!",
    "sent a powerful message!",
    "closed the show with authority!",
    "displayed brutal power!",
    "was unstoppable in the octagon!",
    "delivered a highlight-reel knockout!",
    "sent their opponent crashing to the canvas!",
    "put their opponent to bed!",
    "demonstrated pure knockout power!",
    "showed they are a force to be reckoned with!",
    "sealed the victory with a bang!",
    "unleashed a thunderous strike!",
    "left the crowd in awe!",
    "displayed pinpoint accuracy!",
    "executed a flawless knockout!",
    "overwhelmed their opponent with power!",
    "proved their knockout prowess!",
    "showed off their KO skills!",
    "ended the fight in dramatic fashion!",
    "left no doubt with that finish!",
    "showed true knockout artistry!",
    "made their opponent hit the deck!",
    "closed the fight with a spectacular KO!",
    "proved their knockout power is unmatched!",
    "delivered a bone-crushing blow!",
    "showed why they are a feared striker!",
    "landed a fight-ending strike!",
    "finished with a thunderous KO!",
    "put their opponent down for the count!",
    "left their opponent out cold!",
    "showed off their devastating power!",
    "sealed the win with a brutal KO!",
    "delivered a chilling knockout!",
    "proved their dominance with a KO!",
    "shocked the arena with that blow!",
    "displayed incredible knockout power!",
    "brought an end to the fight in style!",
    "showed they are a knockout artist!",
    "sent their opponent into dreamland!",
    "landed a lights-out blow!",
    "closed the show with a knockout!",
    "proved their hands are deadly weapons!",
    "showed why they are a knockout specialist!",
    "left everyone speechless with that KO!",
    "put an exclamation mark on the fight!",
    "finished their opponent in devastating fashion!",
    "displayed the power of a champion!",
    "proved their KO skills are second to none!",
    "delivered a crowd-pleasing knockout!",
    "left their mark with that KO!",
    "ended the fight with a powerful strike!",
    "put on a knockout clinic!",
    "landed a game-changing attack!",
    "sealed their victory with a KO!",
    "showed their opponent no mercy!",
    "unleashed a fight-ending strike!",
    "dominated with a knockout finish!",
    "crushed their opponent with a single blow!",
    "put their opponent out cold in one hit!",
    "delivered a knockout that echoed through the arena!",
    "made their opponent kiss the canvas!",
    "showed incredible knockout precision!",
    "put their opponent's lights out with a perfect strike!",
    "ended the fight with a stunning KO!",
    "proved their power is unstoppable!",
    "left their opponent flat on the mat!",
    "executed a thunderous knockout!",
    "showed why they're a knockout king!",
    "sent their opponent crashing down with authority!",
    "delivered a devastating blow that ended it all!",
    "left their opponent motionless on the ground!",
    "showed ferocious knockout power!",
    "proved they're a knockout master!",
    "ended the fight with a jaw-dropping KO!",
    "showed why they're the ultimate striker!",
    "delivered a strike that could be felt in the nosebleeds!",
    "ended their opponent's night with a single strike!",
    "made the crowd erupt with a stunning KO!",
    "delivered a knockout blow for the ages!",
    "left their opponent out like a light!",
    "showed pure, unadulterated power with that KO!",
    "proved they're a force to be reckoned with in the ring!",
    "showed no mercy with that devastating strike!",
    "put their opponent out of commission with one hit!",
    "made sure their opponent won't forget that one!",
    "proved their knockout power with a single blow!",
    "ended the fight in spectacular fashion!",
    "showed their dominance with a crushing knockout!",
    "left their opponent down and out with a powerful blow!",
    "delivered a knockout that will be replayed for years!",
    "made a lasting impression with that KO!",
    "sent their opponent straight to the canvas!",
    "showed off their devastating striking ability!",
    "ended the fight with a single, perfect strike!",
    "proved they're the ultimate knockout artist!"
]


ACTION_COST = 10